apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo
spec:
  selector:
    matchLabels:
      app: mongo-db
  template:
    metadata:
      labels:
        app: mongo-db
    spec:
      containers:
      - name: db
        image: mongo:latest
        resources:
          limits:
            memory: "1Gi"
            cpu: "500m"
        env:
          - name: MONGO_INITDB_ROOT_USERNAME
            valueFrom:
              secretKeyRef: 
                name: mongocredentials
                key: username
          - name: MONGO_INITDB_ROOT_PASSWORD
            valueFrom:
              secretKeyRef: 
                name: mongocredentials
                key: password
        ports:
        - containerPort: 27017
      - name: explorer
        image: mongo-express:latest
        resources:
          limits:
            memory: "64Mi"
            cpu: "50m"
        env:
          - name: ME_CONFIG_MONGODB_ADMINUSERNAME
            valueFrom:
              secretKeyRef: 
                name: mongocredentials
                key: adminuser
          - name: ME_CONFIG_MONGODB_ADMINPASSWORD
            valueFrom:
              secretKeyRef: 
                name: mongocredentials
                key: adminpassword
          - name: ME_CONFIG_MONGODB_URL
            value: mongodb://root:imroot@localhost:27017/
        ports:
          - containerPort: 8081
---
apiVersion: v1
kind: Service
metadata:
  name: mongodb
spec:
  selector:
    app: mongo-db
  ports:
  - port: 8081
    name: explorer
  - port: 27017
    name: db